### ISSUE TITLE
Handle Systemd ressources using puppet/systemd

### ISSUE THREAD

**Issue by SimonHoenscheid** [puppetlabs/puppetlabs-pe_databases#111]
## Use Case
currently systemd ressources are just files. It would be nicer to handle them in the right way. 

## Describe the Solution You Would Like
Use puppet/systemd to handle systemd files

## Additional Context
This would add puppet/systemd as an dependency to the module

Is this a FR you would merge @MartyEwings?

**Comment by MartyEwings** [comment]
@SimonHoenscheid Id love to be able to, but as this module ships with PE we have to use native resources to achieve its goals, which means we can't ship it with a dependency. Sorry!

**Comment by SimonHoenscheid** [comment]
@MartyEwings Thanks for explaining the background.
