### ISSUE TITLE
pg_repack cron output is logged to the same file and clobbered

### ISSUE THREAD

**Issue by andrewm3** [puppetlabs/puppetlabs-pe_databases#30]
The pg_repack cronjobs all log to the same file and overwrite it when they run, making it difficult to troubleshoot certain jobs.

The logs should be appended or each job should have it's own file.

Relevant code in `manifests/maintenance/pg_repack.pp`:
```
 $logging = "> ${logging_directory}/output.log 2>&1"
```

**Comment by npwalker** [comment]
@andrewm3 I think this was a conscious decision because I didn't want to deal with log rotation.  

Thoughts on how to deal with an ever-growing log?

**Comment by andrewm3** [comment]
I think that's fair. It's more important that each job doesn't clobber the output of the other than keeping a long running record IMO, so perhaps just different files for each one would be sufficient.

**Comment by jarretlavallee** [comment]
Merged in #43
