### ISSUE TITLE
No longer pg_repack resource_events and reports now that they are partitioned

### ISSUE THREAD

**Issue by npwalker** [puppetlabs/puppetlabs-pe_databases#33]
PDB partitioned resource_events here: https://github.com/puppetlabs/puppetdb/pull/3027

Once that change makes it into PE we should remove resource_events from being repacked as the partitioning should remove the bloating problems.

**Comment by npwalker** [comment]
This should be wrapped in a conditional based on PE version we partitioned reports. 

https://github.com/puppetlabs/puppetlabs-pe_databases/blob/master/manifests/maintenance/pg_repack.pp#L66-L71

**Comment by coreymbe** [comment]
Submitted PR :: https://github.com/puppetlabs/puppetlabs-pe_databases/pull/42

**Comment by jarretlavallee** [comment]
Closed by #42
