### ISSUE TITLE
Git repository does not have tags for 1.0.0 or 1.0.1

### ISSUE THREAD

**Issue by slamble** [puppetlabs/puppetlabs-pe_databases#41]
## Describe the Bug
The Puppet Forge states that the last two releases of this module were versions 1.0.0 and 1.0.1. Checking the tags in the master branch reveals that the last tag was for 0.15.0.

## Expected Behavior
The code branch should have tags for 1.0.0 and 1.0.1.

## Steps to Reproduce
1. Go to https://github.com/puppetlabs/puppetlabs-pe_databases/
2. Drop down the branch list, and switch to 'tags'.
3. Look at the list of tags that can be viewed.

## Environment
Not applicable.

**Comment by jarretlavallee** [comment]
Thanks for filing this @slamble. The tags should be available now.
